POST localhost:3500/tour/data

###
GET localhost:3500/tour/code

###
POST localhost:3500/tour
Content-Type: application/json

{
  "sigunguCode": {"name":  "강남구", "code":  1},
  "startDate":  "2024-11-20",
  "period":  "하루",
  "theme": [ { "code": "A0202", "name": "신나게놀기" }]
}
###
GET localhost:3500/tour/info?contenttypeid=관광지&page=1&searchText=치킨

###
GET http://localhost:3500/tour/info?contenttypeid=관광지&page=1

###
POST localhost:3500/users/register
Content-Type: application/json

{
    "email": "bvbv@test.com",
    "password": "admin1234!",
    "confirmPassword": "admin1234!",
    "profileImage": "",
    "nickName" :"aaa"
}

###
GET localhost:3500/users

###
POST localhost:3500/auth/login
Content-Type: application/json

{
  "email": "bvbv@test.com",
  "password": "admin1234!"
}